# Run dependencies versions update
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/third_party" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      pip-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
