name: SpellCheck

on: [push, pull_request]

jobs:
    build:
        name: Run spell check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run a spell check
              uses: crate-ci/typos@v1.16.23
              with:
                config: ./.github/workflows/.spellcheck-conf.toml
